# Generated by Django 5.2.14 on 2026-05-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.SlugField(max_length=120)),
                ('section_type', models.CharField(max_length=80)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
